services:
  app:
    build: .
    image: controle-horas-app
    container_name: controle-horas-app
    restart: on-failure
    env_file:
      - envs/.env.local
    ports:
      - "8080:8080"
    networks:
      - controle-horas-network

networks:
  controle-horas-network:
    driver: bridge
